type: object
required: 
  - owner
  - rules
  - templateString
properties:
  id:
    type: string
    format: uuid
  owner: 
    $ref: SerialRuleset.yaml
  templateString:
    type: string
  chronologyRules:
    type: array
    items: 
      $ref: ChronologyTemplateMetadataRule.yaml
  enumerationRules:
    type: array
    items: 
      $ref: EnumerationTemplateMetadataRule.yaml
  