type: object
required:
  - index
  - metadataType
properties:
  id:
    type: string
    format: uuid
  index:
    type: integer
  metadataType:
    oneOf: 
      - $ref: EnumerationUCTMT.yaml
      - $ref: ChronologyUCTMT.yaml
  userConfiguredMetadataType:
    oneOf:
      - type: string
      - $ref: RefData.yaml